#!/bin/bash
for pageId in `wp post list --post_type=page --fields=ID --format=ids`;
  do 
	  name=`wp post get $pageId --field=name`
	  echo ========== post $pageId = $name ====
	  wp post get $pageId --field=content>.pages/page-$name.wpmu;
  done

